server:
  port: 8080
  servlet:
    context-path: /shopping

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/backend_shop"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: namhien12082003@gmail.com # Địa chỉ email gửi đi
    password: fsvdovmmnhevcocx # Mật khẩu ứng dụng (App password)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
jwt:
  signerKey: "ofXgea3nTz7EDa0fgD6RIKIAwldMpw+tfJ8kju6UQIWfAaIMyzZdbjE9hwHQxdXD"
  valid-duration: 7200 # in second
  refreshable-duration: 72000 # in second